name: API CI

on:
  push:
    paths:
      - "./api/**"
      - ".github/workflows/api-ci.yml"

defaults:
  run:
    working-directory: ./api

jobs:
  build:
    unit-test:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Use Node.js
          uses: actions/setup-node@v2
          with:
            node-version: "16"
            cache: 'npm'
            cache-dependency-path: '**/package-lock.json'
        - name: Install dependencies
          shell: bash
          run: npm ci
        - name: Run tests
          shell: bash
          run: npm run test
